name: Deploy to WP Engine
on:
  workflow_dispatch:
    inputs:
      WPEDestinationENV:
        description: Where to Deploy?
        type: choice
        required: true
        default: development
        options:
          - development
          - staging
          - production

      WPEDestinationENV:
        description: Install required WordPress plugins?
        type: boolean
        default: false

      WPEClearCache:
        description: Clear WP Cache post deployment?
        type: boolean
        default: true

  env:
    ENVIRONMENT: ${{ inputs.WPEDestinationENV }}
    CLEARCACHE: ${{ inputs.WPEClearCache }}

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install NPM
      run: npm install -g npm@latest

    - name: Install packages
      run: npm install

    - name: Build assets
      run: npm build

    - name: Set WPEngine Environment
      run: |
        case "${{ env.ENVIRONMENT }}" in
          development)
            echo "WPE_ENV=${{ vars.WPE_DEV_ENV }}" >> $GITHUB_ENV
            ;;
          staging)
            echo "WPE_ENV=${{ vars.WPE_STAGING_ENV }}" >> $GITHUB_ENV
            ;;
          production)
            echo "WPE_ENV=${{ vars.WPE_PROD_ENV }}" >> $GITHUB_ENV
            ;;
          *)
            echo "Unsupported environment: ${{ env.ENVIRONMENT }}"
            exit 1
            ;;
        esac

    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        WPE_ENV: $WPE_ENV
        REMOTE_PATH: "wp-content/themes/bald/"
        PHP_LINT: FALSE
        FLAGS: -azvr --delete --exclude-from=.deployignore
        CACHE_CLEAR: ${{ env.CLEARCACHE }}
        SCRIPT: "deployment/composer-install.sh ${{ secrets.ACF_PRO_KEY }}"